name: bump-version

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bumpr - Bump version when merging Pull Request with specific labels
        uses: haya14busa/action-bumpr@v1.8.1
