name: bump-version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set git user
        run: |
          git config user.name "GitHub actions bot - bump-version"
          git config user.email "<>"

      # - name: DEV commit local changes
      #   run: |
      #     git add -A && git commit -m "Stashing changes" --allow-empty &> /dev/null

      # - name: Checkout the release branch
      #   run: ./.ci/checkout-release.sh

      # - name: Merge master
      #   run: ./.ci/merge-master.sh

      - name: Merge the release branch
        run: ./.ci/merge-release.sh

      - name: Bump package version
        run: ./.ci/bump-package-version.sh

      - name: Publish release
        run: ./.ci/publish-release.sh
