name: bump-version

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set git user
        run: |
          git config user.name "GitHub actions bot - bump-version"
          git config user.email "<>"

      # - name: DEV commit local changes
      #   run: |
      #     git add -A && git commit -m "Stashing changes" --allow-empty &> /dev/null

      # - name: Checkout the release branch
      #   run: ./.ci/checkout-release.sh

      # - name: Merge master
      #   run: ./.ci/merge-master.sh

      - name: Echo
        run: ./.ci/echo.sh

      - name: Bump package version
        run: ./.ci/bump-package-version.sh

      - name: Log git info
        run: ./.ci/echo-git-info.sh

      # - name: Merge the release branch
      #   run: ./.ci/merge-release.sh

      # - name: Publish release
      #   run: ./.ci/publish-release.sh
